<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>IdP.Api</RootNamespace>
    <AssemblyName>IdP.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(SentinelSrc)/Nuvora.Nexus.Sentinel.Core/Nuvora.Nexus.Sentinel.Core.csproj" />
    <ProjectReference Include="$(SentinelSrc)/Nuvora.Nexus.Sentinel/Nuvora.Nexus.Sentinel.csproj" />
    <ProjectReference Include="$(SentinelSrc)/Nuvora.Nexus.Sentinel.AspNetCore/Nuvora.Nexus.Sentinel.AspNetCore.csproj" />
    <ProjectReference Include="$(SentinelSrc)/Nuvora.Nexus.Sentinel.OidcServer/Nuvora.Nexus.Sentinel.OidcServer.csproj" />
  </ItemGroup>

</Project>
